module.exports = [
  "A bird in the hand is worth two in the bush. Unless the bush is Austrailia, then get those birds out of your hand.\nThey're going to kill you.",
  "A frog is faster than a toad. Unless, of course, the frog is sleeping.",
  "If you take it with another grain of salt, your blood pressure will go up.",
  "Time flies when you're having fun: Be boring.",
  "A closed mouth gathers no feet.",
  "All would live long but none would be old.",
  "An apple a day keeps the doctor away, but an onion a day keeps everyone away.",
  "To steal ideas from one person is plagiarism; to steal from many is research - Steven Wright",
  "Borrow money from pessimists – they don’t expect it back - Oscar Wilde",
  "A clear conscience is usually the sign of a bad memory.",
  "42.7% of all statistics are made up on the spot.",
  "Ambition is a poor excuse for not having enough sense to be lazy .",
  "If at first you don’t succeed, destroy all evidence that you tried.",
  "The sooner you fall behind, the more time you’ll have to catch up.",
  "If Barbie is so popular, why do you have to buy her friends?",
  "Everyone has a photographic memory; some just don’t have film.",
  "If your car could travel at the speed of light, would your headlights work?",
  "Hard work pays off in the future, laziness pays off now.",
  "If you want the rainbow, you got to put up with the rain.",
  "The body is wise, the confusion is from the mind - Aniekee Tochukwu Ezekiel",
  "When wise man quits learning, he will be more senile onwards - Toba Beta",
  "Comparing yourself to others dwarfs your imagination - Bangambiki Habyarimana",
  "Only the man who thinks himself a fool is as wise as he thinks - Criss Jami",
  "A wise man understands, an intelligent man knows, but a fool pretends to know - Debasish Mridha",
  "It's not true that I had nothing on. I had the radio on - Marilyn Monroe",
  "If a book about failures doesn't sell, is it a success? - Jerry Seinfeld",
  "I came from a real tough neighborhood. Once a guy pulled a knife on me. I knew he wasn't a professional, the knife had butter on it - Rodney Dangerfield",
  "Never miss a good chance to shut up. - Will Rogers",
  "Opera is when a guy gets stabbed in the back and, instead of bleeding, he sings - Robert Benchley",
  "A Penny Saved is a Penny Earned - Ben Franklin",
  "In the end, we will remember not the words of our enemies, but the silence of our friends. – Martin Luther King Jr",
  "Empty cans make the most noise.",
  "The wisest of people in this world are those that admit when they are wrong.",
  "Those who fail to prepare, are preparing to fail",
  "Being quiet is fine, most people don't listen anyways.",
  "Never expect anything. This way, you'll never be disappointed.",
  "Never challenge an old man, because if you lose, you've lost to an old man, and if you win, so what?",
  "If you can't cook don't tell someone their food needs salt.",
  "When 'you' change, everything else changes.",
  "Care about what other people think and you wil always be their prisoner. - Lao Tzu",
  "Tough times never last, but tough people do.",
  "A wise man's actions speak for himself.",
  "People should not be afraid of their governments, governments should be afraid of their people.",
  "Everbody makes mistakes, thats why they put erasers on the end of pencils",
  "What sounds foolish to the wise, sounds wise to the foolish.",
  "To prevent is better than to cure.",
  "50% of the solution is to put your hands on the problem.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail",
  "Those who know do not speak. Those who speak do not know. - Lao Tzu",
  "Stop thinking, and end your problems. - Lao Tzu",
  "Wisdom is not knowledge. Therefore it’s not knowing that 2+2=4, but how/why 2+2=4",
  "Arguing with a fool proves there are two.",
  "Bravery isn’t not being afraid. Bravery is being afraid but doing it anyway",
  "Don't look in mirrors to see the future, cause all you will see is what is behind you.",
  "Nothing is to be gained by arguing with fools. Nothing can be gained by reasoning with ignorant people. – Dr T.P.Chia",
  "It’s never the cards your dealt, but always how you play the hand.",
  "The things you want to die for, are the things you live for…",
  "Endless time is spent trying to figure others out, when deep down, you’re the one that needs discovering.",
  "A wise man speaks. A wiser man writes.",
  "Life’s Battle is never won by the fastest or the strongest,but by the man who thinks he can",
  "Predictions are nothing but warnings, until they happen",
  "Never give up on your dreams, because one day you might regret it.",
  "Imagination is the Key to Innovation",
  "To understand others…you have to understand yourself first!",
  "A wise guy once said, “I don’t know, ask a girl.",
  "My abilities are only limited by those who try to test them",
  "Better to live one day as a lion, than a thousand years as a lamb.",
  "The man who thinks he knows everything will eventually find he knows nothing.",
  "Seeking wisdom is a fool’s errand for wisdom is learnt, not taught.",
  "Look at everything as though you were seeing it either for the first or last time."
]
