module.exports = [
  "A bird in the hand is worth two in the bush. Unless the bush is Austrailia, then get those birds out of your hand.\nThey're going to kill you.",
  "A frog is faster than a toad. Unless, of course, the frog is sleeping.",
  "If you take it with another grain of salt, your blood pressure will go up.",
  "Time flies when you're having fun: Be boring.",
  "A closed mouth gathers no feet.",
  "All would live long but none would be old.",
  "An apple a day keeps the doctor away, but an onion a day keeps everyone away.",
  "To steal ideas from one person is plagiarism; to steal from many is research - Steven Wright",
  "Borrow money from pessimists – they don’t expect it back - Oscar Wilde",
  "A clear conscience is usually the sign of a bad memory.",
  "42.7% of all statistics are made up on the spot.",
  "Ambition is a poor excuse for not having enough sense to be lazy .",
  "If at first you don’t succeed, destroy all evidence that you tried.",
  "The sooner you fall behind, the more time you’ll have to catch up.",
  "If Barbie is so popular, why do you have to buy her friends?",
  "Everyone has a photographic memory; some just don’t have film.",
  "If your car could travel at the speed of light, would your headlights work?",
  "Hard work pays off in the future, laziness pays off now.",
  "If you want the rainbow, you got to put up with the rain.",
  "The body is wise, the confusion is from the mind - Aniekee Tochukwu Ezekiel",
  "When wise man quits learning, he will be more senile onwards - Toba Beta",
  "Comparing yourself to others dwarfs your imagination - Bangambiki Habyarimana",
  "Only the man who thinks himself a fool is as wise as he thinks - Criss Jami",
  "A wise man understands, an intelligent man knows, but a fool pretends to know - Debasish Mridha",
  "It's not true that I had nothing on. I had the radio on - Marilyn Monroe",
  "If a book about failures doesn't sell, is it a success? - Jerry Seinfeld",
  "I came from a real tough neighborhood. Once a guy pulled a knife on me. I knew he wasn't a professional, the knife had butter on it - Rodney Dangerfield",
  "Never miss a good chance to shut up. - Will Rogers",
  "Opera is when a guy gets stabbed in the back and, instead of bleeding, he sings - Robert Benchley",
  "A Penny Saved is a Penny Earned - Ben Franklin",
  "In the end, we will remember not the words of our enemies, but the silence of our friends. – Martin Luther King Jr",
  "Empty cans make the most noise.",
  "The wisest of people in this world are those that admit when they are wrong.",
  "Those who fail to prepare, are preparing to fail",
  "Being quiet is fine, most people don't listen anyways.",
  "Never expect anything. This way, you'll never be disappointed.",
  "Never challenge an old man, because if you lose, you've lost to an old man, and if you win, so what?",
  "If you can't cook don't tell someone their food needs salt.",
  "When 'you' change, everything else changes.",
  "Care about what other people think and you wil always be their prisoner. - Lao Tzu",
  "Tough times never last, but tough people do.",
  "A wise man's actions speak for himself.",
  "People should not be afraid of their governments, governments should be afraid of their people.",
  "Everbody makes mistakes, thats why they put erasers on the end of pencils",
  "What sounds foolish to the wise, sounds wise to the foolish.",
  "To prevent is better than to cure.",
  "50% of the solution is to put your hands on the problem.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail",
  "Those who know do not speak. Those who speak do not know. - Lao Tzu",
  "Stop thinking, and end your problems. - Lao Tzu",
  "Wisdom is not knowledge. Therefore it’s not knowing that 2+2=4, but how/why 2+2=4",
  "Arguing with a fool proves there are two.",
  "Bravery isn’t not being afraid. Bravery is being afraid but doing it anyway",
  "Don't look in mirrors to see the future, cause all you will see is what is behind you.",
  "Nothing is to be gained by arguing with fools. Nothing can be gained by reasoning with ignorant people. – Dr T.P.Chia",
  "It’s never the cards your dealt, but always how you play the hand.",
  "The things you want to die for, are the things you live for…",
  "Endless time is spent trying to figure others out, when deep down, you’re the one that needs discovering.",
  "A wise man speaks. A wiser man writes.",
  "Life’s Battle is never won by the fastest or the strongest,but by the man who thinks he can",
  "Predictions are nothing but warnings, until they happen",
  "Never give up on your dreams, because one day you might regret it.",
  "Imagination is the Key to Innovation",
  "To understand others…you have to understand yourself first!",
  "A wise guy once said, “I don’t know, ask a girl.",
  "My abilities are only limited by those who try to test them",
  "Better to live one day as a lion, than a thousand years as a lamb.",
  "The man who thinks he knows everything will eventually find he knows nothing.",
  "Seeking wisdom is a fool’s errand for wisdom is learnt, not taught.",
  "Look at everything as though you were seeing it either for the first or last time.",
  "You are only young once but you can be immature forever",
  "It’s not how many friends you miss. It’s how many friends you made along the way",
  "Everybody has a different way to view the world.",
  "God gave you two ears and one mouth so you can listen twice as much as you talk",
  "Don’t let the fear of striking out keep you away from playing the game.",
  "What we do in life echos in eternity.",
  "How can you discover new oceans, if you’re afraid to lose site of the shore.",
  "I am who I want to be, not what others see me as.",
  "If you want to leave a footprint, Don’t drag your feet.",
  "Knowledge is whatever remains after you forgotten what you’ve learned.",
  "Flying is the second hardest thing known to man, landing is the first.",
  "When you get up, don’t push someone down.",
  "I’d rather be a loser than a quitter.",
  "A hero doesn’t need to speak, when he is gone the world will speak for him.",
  "F.A.I.L – First Attempt at learning",
  "A man with a lot of knowledge and no character is a dangerous man.",
  "Never burn a bridge you might have to walk across.",
  "A person’s real character is shown at the time of the worst situation.",
  "People may doubt what you say but they always believe what you do.",
  "Some people walk in the rain, others just get wet. – Roger Miller",
  "If you can’t explain it simply, you don’t understand it well enough. – Albert Einstein",
  "Today is forever, tomorrow never comes",
  "He who angers you, controls you.",
  "Look at what’s in front of you, don’t look back or look far in to the distance.",
  "Never buy a car that you can’t push",
  "Knowledge is knowing tomato is a fruit and wisdom is not putting tomatoes in a fruit salad. ",
  "Enjoy what you have today. Either it will be gone, or you will be gone.",
  "The perfect time to start something never arrives.",
  "Not having any talents just means that you have to try harder",
  "A smart person will give you smart answers, but a wise person will ask you smart questions.",
  "Talent is like flower, it needs watering.",
  "Small minds have wishes, Great minds have purposes.",
  "Learn to give without saying anything, but when receiving say something.",
  "If you think only of yourself, You will be the only one thinking of you.",
  "Control your fear or it will control you.",
  "Everybody is a genius. But if you judge a fish by its ability to climb a tree, it will spend its whole life believing that it is stupid. – Albert Einstein",
  "Never start a fight with someone who has nothing to lose.",
  "Don’t use a cannon to kill a mosquito.",
  "We spend too much time thinking and not enough time doing.",
  "Anything you ever want in life is just outside your comfort zone.",
  "A father who teaches his son how to lie, will one day lie to him.",
  "Its better to hurt someone honestly with the truth rather than to mislead them with a lie.",
  "Make your last words your true words.",
  "Do not degrade yourself to upgrade anyone else.",
  "The key to everything is patience. You get the chicken by hatching the egg, not by smashing it open!",
  "Don’t look where you fell, but where you slipped.",
  "There are some things that money can’t buy…like manners, morals and integrity.",
  "Be the type of person you want to meet.",
  "Excuses are the nails that build a house of a failure.",
  "Blowing out someone else’s candle doesn’t make yours shine any brighter.",
  "There are three sides to every story…your side..my side…and the right side.",
  "Knowing yourself is the beginning of all wisdom. – Aristotle",
  "One dollar earned is better than 5 dollars found.",
  "Try being informed instead of just opinionated.",
  "Do not wish life were easier, wish you were tougher. – Dr T.P.Chia",
  "A negative mind will never give you a positive life.",
  "A blind man can see as well as a man with heightened vision. For seeing is not only looking, for it is also to understand.",
  "A wise man listens no matter how stupidly someone is talking.",
  "Knowledge talks, wisdom listens. – Jimi Hendrix",
  "Why is abbreviation such a long word?"
]
